# Generated by Django 5.1.2 on 2024-10-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start", models.TimeField()),
                ("stop", models.TimeField()),
                ("ids", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("day_of_week", models.CharField(max_length=10)),
                ("time_slots", models.ManyToManyField(to="scheduler.timeslot")),
            ],
        ),
    ]
