# Generated by Django 5.1.2 on 2024-10-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="time_slots",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="day_of_week",
        ),
        migrations.AddField(
            model_name="schedule",
            name="schedule",
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name="TimeSlot",
        ),
    ]
